### ISSUE TITLE
switch to Lazy global instead of Context+Mutex

### ISSUE THREAD

**Issue by benmkw** [4bb4/implot-rs#7] opened 2020-10-23 16:22 UTC
https://github.com/4bb4/implot-rs/blob/cdc7e273c0b9cd92775e8841f6cf39f6c7283b1f/src/context.rs#L30-L34

It seems to me like it would be easier for the user if it would just have something like

```rust
static CONTEXT: Lazy<CONTEXT> = Lazy::new(|| {
    Context::create()
});
```
and then not have the PlotUi parameter everywhere.

because there will always only ever be one context? This could still be wrapped in a mutex if necessary.

**Comment by 4bb4** [comment] 2020-10-24 07:11
I'm aware of lazy globals and agree that from a pure user perspective, this appears easier to use, but there are a few reasons I'm not using one here:
* You are correct that there can only be one context right now, but that limitation will likely go away in the future. This is not visible in the code here, because I've removed the code for handling multiple contexts when taking over this code from imgui-rs - I've done that because I don't know whether implot itself currently supports multiple "suspended" contexts (it should, after all imgui itself does, but I have not checked).

* Implot itself makes the context explicit as well (https://github.com/epezent/implot#integration), and I want to make the usage of the Rust bindings match the usage of the original library aside from safety functionality. I'm already not sure about another interface change I made compared to the original implot, for example (https://docs.rs/implot/0.1.0/implot/struct.PlotBars.html#method.plot has `axis_positions` and `bar_values` instead of the less descriptive `x` and `y` in the original). Such changes make it harder to maintain the bindings upstream - imagine the context initialization now gets an argument in the future that the user can configure, for example. Note that implot itself used to have an internal, lazily initialized context, and switched away from that. Imgui also uses a context, also explicitly, in both the C++ as well as the Rust version. I think being consistent is valuable.

* I generally don't like implicit internal state. If a library uses a context, that should be made visible to the user, even if it causes some inconvenience, and even if it is only a singleton for the moment.

I'll add some reasoning to the code itself, because that this question came up shows that my documentation is not adequate yet.

**Comment by benmkw** [comment] 2020-10-24 07:19
I agree on all points 👍 and also your documentation was really helpful! 

I think i want to experiment without the global state for my imnodes port just because it makes it less typing work and I’d be willing to make an API break later if that seemed necessary but that certainly does not mean that I think this project should do the same. 

There is also some things about the builder and tokens where there is a tradeoff between correctness and efficiency where maybe a config flag could be an option to disable some checks but at the moment that seems like not a necessary optimisation and I may need to think about that myself for a bit :)

**Comment by 4bb4** [comment] 2020-10-24 07:23
> I think i want to experiment without the global state for my imnodes port just

:+1:  let me know how it goes. I have not thought about lazy globals that much so far, because I rarely have a case where only one context is possible by design. When there can be multiple contexts, the argument is moot anyway, so I usually don't spend lots of time thinking about it. One data point I have is that in another project where I used to have a lazy global, the users found it surprising and were confused that the library has internal state. That might have just been a lack of proper documentation though.

> There is also some things about the builder and tokens where there is a tradeoff between correctness and efficiency where maybe a config flag could be an option to disable some checks [...]

That is an interesting idea. I like the approach of "safety by default, but one can opt into performance if desired". I have not done any benchmarking whatsoever of the code so far - I think it's likely that a token per plot is not an issue, but maybe if you have a token per line you draw and you draw a thousand lines, things become more problematic.

Another way things could go is that similar to the project mentioned in https://github.com/epezent/implot#integration, https://github.com/mahilab/mahi-gui, there could be something in Rust that "just readies all those libraries and makes it easy to get a plot" - this could then also include your nodes library, for example.

**Comment by benmkw** [comment] 2020-10-24 07:55
> I think i want to experiment without the global state for my imnodes port just

Actually what I wanted to say was „without the parameter to all methods and just using implicit global state“ but I’ll have to see. 

> the users found it surprising and were confused that the library has internal state.

Yes that definitely could have just as well been me as a user haha 

> this could then also include your nodes library, for example

I think this can be done in a separate library.
Imgui wgpu backend will probably also get an easy to use function to setup a fullscreen imgui context and then make using imgui with wgpu basically be a few lines of code instead of copy pasting a whole lot. 
So another library could package all those things up or it could also just be docs that show how to pull in those dependencies, idk yet.

I definitely think imnodes can work just as well as this library and basically copy most of the design, there is „just“ the typing work that needs to be done :) 

> That is an interesting idea. I like the approach of "safety by default, but one can opt into performance if desired".

Yes I think it should be easy to have a cfg flag disable the mutex and the token drop checks and the helper members required for that but I’m also not sure how common it is to plot to imgui from multiple threads. I’d like to think that this is more of an edge case. 

It’s important to keep in mind when creating these options that features have to be additive though https://dev.to/rimutaka/cargo-features-explained-with-examples-194g

**Comment by 4bb4** [comment] 2021-03-14 20:19
Closing this as I currently don't have any plans to switch to a lazy global.

**Closed as completed by 4bb4** 2021-03-14 20:19 UTC
